# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b06af97e12d90ec898bbdcaea8e57bf49c40e0c2626a2b7acb45385d2ff7a8f2a4a71b5abffe9755036ec439a9b7496ea76d42bbf8080c6386f38aa5488c363

test:
  secret_key_base: 05a10f3056e8d1d7e80ab6cf66e256c055a3ce31bd297d3ef01d064bc093d2025e4834ecae0f0513a769c20917444d5797dbd3a58f4df4a628a51815369f1040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
